export const dummy_data = [
	{
		id: 1,
		case_number: "123ABC",
		status: "in_progress",
		status_text: "Pending file submission",
		description: "",
		client_id: 2,
		solicitor_id: 1,
		solicitor: {
			id: 1,
			email: "talha_qureshi@hotmail.com",
			first_name: "Talha",
			last_name: "Qureshi",
			phone: "213-986-9911",
		},
		client: {
			id: 2,
			email: "basil@meer.com",
			first_name: "Basil",
			last_name: "Meer",
			phone: "307-290-555",
		},
	},
	{
		id: 2,
		case_number: "1122AABB",
		status: "on_hold",
		status_text: "Client reconsidering decision",
		description: "",
		client_id: 3,
		solicitor_id: 1,
		solicitor: {
			id: 1,
			email: "talha_qureshi@hotmail.com",
			first_name: "Talha",
			last_name: "Qureshi",
			phone: "213-986-9911",
		},
		client: {
			id: 3,
			email: "matt@murdok.com",
			first_name: "Matt",
			last_name: "Murdok",
			phone: "335-770-3613",
		},
	},
	{
		id: 3,
		case_number: "ABC123",
		status: "completed",
		status_text: "Property sold",
		description: "",
		client_id: 4,
		solicitor_id: 1,
		solicitor: {
			id: 1,
			email: "talha_qureshi@hotmail.com",
			first_name: "Talha",
			last_name: "Qureshi",
			phone: "213-986-9911",
		},
		client: {
			id: 4,
			email: "stephanie@crawfard.com",
			first_name: "Stephanie",
			last_name: "Crawfard",
			phone: "321-457-5835",
		},
	},
];
